### PR TITLE
Increment the age of the response #59

### PR DESCRIPTION
**Pull request by bmancone**
This fixes issue #59.

### CODE REVIEW

**Comment by mtdowling** [comment]
Should we just use the Date header?

**Comment by bmancone** [comment]
Not sure. Relying on the Date header assumes that the local clock is synchronized to the server's clock, which feels more brittle ?

Moreover, varnish (for instance) does not have the same behaviour regarding the date header in version 3 and version 4.
* Version 3 overrides the date when it serves the response.
* Version 4 keeps the date as given from the backend (to be more [RFC compliant](https://www.varnish-cache.org/trac/changeset/89870e0bbd785964c322e1e453f492d747731c88/)).

The calculation of the amount of time since the response was stored would then differ depending if it was served by v3 or v4.



The code in this PR (relying on storing the local date when the Response entered our cache) implements exactly the calculation mentioned at the end of the [Calculating Age](https://tools.ietf.org/html/rfc7234#section-4.2.3) section in the RFC :
> resident_time = now - response_time;
> current_age = corrected_initial_age + resident_time

(with `corrected_initial_age == Utils::getResponseAge($response)` and `response_time == what we store in X-Guzzle-Cache-Date`)

**Comment by rolebi** [comment]
Would love to this this PR merged : )

**Comment by mtdowling** [comment]
This needs tests and then it can be merged.

**Comment by bmancone** [comment]
@mtdowling, I added an integration test. Let me know if this needs changes.

**Pull request merged**
