### PR TITLE
Cache entries with the same ttl as the page

### PR DESCRIPTION
**Pull request by JLepeltier**

### CODE REVIEW

**Comment by goetas** [comment]
:+1:  tests?

**Comment by goetas** [comment]
i had the same problem, 

@mtdowling any chance to see this meged?

**Comment by ryanhughes** [comment]
Can you update the pull request to only include the original f3b6cb1 commit? It will have a better chance of being merged.

**Comment by GrahamCampbell** [comment]
Thanks for the PR, but I'm going to close this since this repo has been EOL for a while now.

**Pull request closed without merging**
